### ISSUE TITLE
Consumer xml file missing

### ISSUE THREAD

**Issue by ivanfig** [RexMorgan/Itch#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\idf\Documents\c#\Itch\src\Itch.Consumer\Itch.Consumer.log4net.xml" because it was not found.	Itch.Consumer

**Comment by RexMorgan** [comment]
@ivanfig This was a project I was playing around with years ago (2011) and I won't be fixing any issues with it. Thank you for reporting, though.

https://rexflex.net/articles/scratching-the-itch/
